services:
  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: myapp
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data: